### ISSUE TITLE
Other Models result in error

### ISSUE THREAD

**Issue by TheJedinator** [rikhuijzer/ata#35]
When I try other models that I have access to I receive an error consistently. Sometimes it starts printing the response, sometimes it only prints the error...

```json
{
  "data": {
    "id": "chatcmpl-91yH74w78DzwnwgfeB8pH1dvl7raP",
    "object": "chat.completion.chunk",
    "created": 1710257053,
    "model": "gpt-4-0613",
    "system_fingerprint": null,
    "choices": [
      {
        "index": 0,
        "delta": { "content": "Weather" },
        "logprobs": null,
        "finish_reason": null
      }
    ]
  }
}
```

my toml is set as 

```toml
api_key = "REDACTED"
model = "gpt-4"
max_tokens = 2048
temperature = 0.8
```
